### ISSUE TITLE
Resolve server names on every connection.

### ISSUE THREAD

**Issue by gdhbashton** [UlricE/pen#11]
I have been trying to use Pen on a DMZ host to expose internal services to certain outside visitors (locked down by IP address).

The natch is the service is an AWS ELB - this has a static hostname, but the A records will change almost every day. Pen does not re-evaluate the records, so that means I have to restart Pen roughly once a day - not ideal.

The connection traffic is extremely low - maybe 10-20 connections per day, so may I ask for 'always resolve' as an option to Pen?  Clearly this option would not be suitable for mid-high traffic HTTP, but for this use case (proxying MSSQL TCP 1433) it would be perfect!

Cheers,
Gavin.

**Comment by UlricE** [comment]
Hm, I see how restarting Pen to clear the cache is inconvenient. On the other hand, resolving on every connect is very costly in terms of latency.

How does this work with AWS btw - if the IP address of the service changes, won't the connection break?

My suggestion would be to use penctl to reassign the server addresses. That will resolve the hostnames without restarting Pen.

**Comment by gdhbashton** [comment]
Ah that's interesting... after some simple `tcpdump` confirmation, I'm happy that `pen` will re-resolve the backend server even if the hostname has not changed.

The only caveat there is that even after issuing `penctl localhost:9997 server 0 address my.hostname.internal` , any open connections through `pen` are untouched, relying on the client to timeout and retry. That's still an improvement from the previous state!

Thank you for your suggestion - I'll throw that `penctl` line into an hourly cronjob.

**Comment by UlricE** [comment]
Closing this, since Pen can be made to re-resolve addresses using penctl.
