### ISSUE TITLE
Transparent Reverse Proxy on Centos6/7 is showing the load balancer IP in the source address

### ISSUE THREAD

**Issue by ankush-grover-3pg** [UlricE/pen#15]
Hi,

I have followed the below page for setting the transparent reverse proxy on Centos6/7 but in the logs I am still seeing the Load Balancer IP. Actually I am trying to setup graylog2 (log analyzer) with the multiple servers and for architecture I need a LB which can run forward the request to the different graylog servers. 

https://github.com/UlricE/pen/wiki/Transparent-Reverse-Proxy

Presently only 1 graylog server is running and accepting tcp connections on port 21514 ports and the pen lb is running on port 22514 on the same host. A few syslog clients (linux machines) are forwarding their logs on to pen lb port 22514 and which in turn forwarding to to port 21514 of graylog server. In the graylog servers I see the logs are coming with the source ip of lb whereas pen is configured to run in the transparent environment. I have tried pen in transparent mode both with the rpm (epel repo) and building it from source and in both the cases lb ip is coming as the source ip. The issue is on Centos 6 as well as on Centos 7.

What could be the reason for transparent reverse proxy not working properly. I have pasted the pen configuration file, startup script (with transparent option) and logs of pen

pen.conf file

LOGFILE=/var/log/pen.log
WEBFILE=/var/www/html/pen/webstats.html
CONTROL=172.31.10.58:10080
MAX_CONNECTIONS=500
PORT=22514
BACKEND=2
SERVER0=172.31.10.59:21514
SERVER1=172.31.10.58:21514

/etc/init.d/pend file (startup control file)

#!/bin/bash

# pend: Start/Stop Pend
# chkconfig: - 90 10
# description: Pen is a light weight simple load balancer.
# pidfile: /var/run/pen.pid

. /etc/rc.d/init.d/functions
. /etc/sysconfig/network
. /etc/pen.conf

LOCKFILE="/var/lock/subsys/pen"
PID=/var/run/pen.pid
PROG=/usr/bin/pen

RETVAL=0
start() {
   echo -n $"Starting Pend: "
   SERVER=`grep "^SERVER" /etc/pen.conf | cut -d= -f2`
   daemon $PROG -w $WEBFILE -x $MAX_CONNECTIONS -p $PID -l $LOGFILE -C $CONTROL -S $BACKEND -r $PORT $SERVER -o transparent -d
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && touch $LOCKFILE
   return $RETVAL
}
stop() {
   echo -n $"Stopping Pend: "
   killproc $PROG
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && rm -f $PID $LOCKFILE
   return $RETVAL
}
case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   status)
      status pend
      ;;
   restart)
      stop
      start
      ;;
   *)
      echo $"Usage: $0 {start|stop|status|restart}"
      exit 1
esac
exit $?

Iptables rules for mangle table

iptables -t mangle -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DIVERT     tcp  --  anywhere             anywhere             socket

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain DIVERT (1 references)
target     prot opt source               destination         
MARK       all  --  anywhere             anywhere             MARK set 0x1
ACCEPT     all  --  anywhere             anywhere            

Logs file

172.32.1063 1441278230 172.31.10.59 0 2015-09-03T07:03:50.947734-04:00 jiraca-test rsyslogd -  [origin software="rsyslogd" swVersion="7.
172.32.1063 1441278248 172.31.10.59 0 2015-09-03T07:04:08.189846-04:00 jiraca-test xinetd 24232 START: nrpe pid=24440 from=::ffff:172.16
172.32.1063 1441278248 172.31.10.59 0 2015-09-03T07:04:08.204888-04:00 jiraca-test xinetd 24232 EXIT: nrpe status=0 pid=24440 duration=0
172.32.1063 1441278250 172.31.10.59 0 2015-09-03T07:04:10.239426-04:00 jiraca-test sshd 24444 Failed password for root from 172.31.10.28
172.32.1063 1441278250 172.31.10.59 0 2015-09-03T07:04:10.437364-04:00 jiraca-test sshd 24444 Failed password for root from 172.31.10.28
172.32.1063 1441278250 172.31.10.59 0 2015-09-03T07:04:10.438355-04:00 jiraca-test sshd 24444 Connection closed by 172.31.10.28 [preauth
172.32.1063 1441278250 172.31.10.59 0 2015-09-03T07:04:10.777407-04:00 jiraca-test sshd 24446 Failed password for root from 172.31.10.28
172.32.1063 1441278250 172.31.10.59 0 2015-09-03T07:04:10.953666-04:00 jiraca-test sshd 24446 Failed password for root from 172.31.10.28
172.32.1063 1441278250 172.31.10.59 0 2015-09-03T07:04:10.954467-04:00 jiraca-test sshd 24446 Connection closed by 172.31.10.28 [preauth
172.32.1063 1441278251 172.31.10.59 0 2015-09-03T07:04:11.291114-04:00 jiraca-test sshd 24448 Failed password for root from 172.31.10.28

Thanks & Regards

Ankush Grover

**Comment by UlricE** [comment]
Do you have one or two network interfaces in the Pen host? It looks as though the client and servers are on the same network segment. The Wiki page isn't very explicit but the relevant section is this:

> In this example, debian2 is the client with IP 192.168.100.2 and debian3 is the server with IP 192.168.101.3. Pen sits in between with IP addresses 192.168.100.11 and 192.168.101.10. Debian2 and debian3 have static routes set up so they can reach each other through the host running Pen.

This is to force the return traffic through Pen so the "spoofed" addresses can be unspoofed.

**Comment by ankush-grover-3pg** [comment]
There is only 1 network interfaces on the pen host?? So there should be 2 different network interfaces for the transparent reverse proxy to work??

**Comment by UlricE** [comment]
Yes. Imagine that the client is 1.1.1.1, Pen's address is 2.2.2.2 and the server is 2.2.2.3. The client connects from 1.1.1.1 to 2.2.2.2; Pen connects from 1.1.1.1 to 2.2.2.3; the server tries to respond from 2.2.2.3 to 1.1.1.1 **bypassing Pen**.

What you can do is use Direct Server Return instead. It not only works with the network topology you have but actually *requires* that configuration. You'll still want a separate network interface as the one used for DSR can't be used for management.

**Comment by UlricE** [comment]
Closing this, since it is a configuration issue and not a Pen issue.
