### ISSUE TITLE
suggestion: create the file if not found

### ISSUE THREAD

**Issue by yodog** [UlricE/pen#16]
Hello.

About the log message `Can't write to /var/www/pen/webstats.html`.

I'd like to suggest that the file (or full path) would be created if it doesnt exist.

**Comment by UlricE** [comment]
Like with the control port, creating missing path components could accidentally overwrite something or be used as an attack vector. It seems like something that can be handled by the start script.

**Comment by yodog** [comment]
ok again.

since you mentioned the start script, how can i make pen read the config from a file instead of passing arguments to ./pen ?

**Comment by UlricE** [comment]
-F cfgfile

**Comment by UlricE** [comment]
Closing this, since the start script can ensure that the full path to the stats file is available, if needed.
