### ISSUE TITLE
suggestion: allow root to open control port

### ISSUE THREAD

**Issue by yodog** [UlricE/pen#17]
Hello.

About the log message `Won't open control port running as root; use -u to run as different user`.

I'd like to suggest that `root`, being a superuser, could also open the control port.

**Comment by UlricE** [comment]
The message is to avoid accidentally overwriting something valuable and to discourage unnecessarily running as root in a production environment. You can however use the -u option and open the control port as root if you really want to:

pen -u root -C ./ctl -U 53 8.8.8.8

**Comment by yodog** [comment]
ok. thanks.
