### ISSUE TITLE
freebsd 10: pen chooses backup carp address as src

### ISSUE THREAD

**Issue by hcoin** [UlricE/pen#33]
Freebsd 10, ip4:

router1 192.168.1.20/24  carp master vhid 192.168.1.1
router 2 192.168.1.21  CARP VHID backup 192.168.1.1
named running on 192.168.1.100, another named on 192.168.1.101
 pen -U 53 192.168.1.100:53 192.168.1.101:53  
on router 2 will transmit packets with source address 192.168.1.1 -- causing all replies to packets sent by pen on router to go instead to router 1.

**Comment by UlricE** [comment]
Option added to select local address for upstream connections. The command lines would be something like

    pen -U -O "source 192.168.1.20" 53 192.168.1.100 192.168.1.101

and

    pen -U -O "source 192.168.1.21" 53 192.168.1.100 192.168.1.101

This is in latest Git. Please try it out and if it works out it goes into the next release.

**Comment by UlricE** [comment]
Closing this since the fix is in 0.34.0.
